const data01 = [{
	"value": "浙江省",
	"label": "浙江省",
	"children": [{
		"value": "杭州市",
		"label": "杭州市",
		"children": [{
			"value": "滨江区",
			"label": "滨江区",
			"children": []
		}, {
			"value": "淳安县",
			"label": "淳安县",
			"children": []
		}, {
			"value": "富阳区",
			"label": "富阳区",
			"children": []
		}, {
			"value": "拱墅区",
			"label": "拱墅区",
			"children": []
		}, {
			"value": "建德市",
			"label": "建德市",
			"children": []
		}, {
			"value": "江干区",
			"label": "江干区",
			"children": []
		}, {
			"value": "临安市",
			"label": "临安市",
			"children": []
		}, {
			"value": "上城区",
			"label": "上城区",
			"children": []
		}, {
			"value": "桐庐县",
			"label": "桐庐县",
			"children": []
		}, {
			"value": "西湖区",
			"label": "西湖区",
			"children": []
		}, {
			"value": "下城区",
			"label": "下城区",
			"children": []
		}, {
			"value": "萧山区",
			"label": "萧山区",
			"children": []
		}, {
			"value": "余杭区",
			"label": "余杭区",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "湖州市",
		"label": "湖州市",
		"children": [{
			"value": "安吉县",
			"label": "安吉县",
			"children": []
		}, {
			"value": "长兴县",
			"label": "长兴县",
			"children": []
		}, {
			"value": "德清县",
			"label": "德清县",
			"children": []
		}, {
			"value": "南浔区",
			"label": "南浔区",
			"children": []
		}, {
			"value": "吴兴区",
			"label": "吴兴区",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "嘉兴市",
		"label": "嘉兴市",
		"children": [{
			"value": "海宁市",
			"label": "海宁市",
			"children": []
		}, {
			"value": "海盐县",
			"label": "海盐县",
			"children": []
		}, {
			"value": "嘉善县",
			"label": "嘉善县",
			"children": []
		}, {
			"value": "南湖区",
			"label": "南湖区",
			"children": []
		}, {
			"value": "平湖市",
			"label": "平湖市",
			"children": []
		}, {
			"value": "桐乡市",
			"label": "桐乡市",
			"children": []
		}, {
			"value": "秀洲区",
			"label": "秀洲区",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "金华市",
		"label": "金华市",
		"children": [{
			"value": "东阳市",
			"label": "东阳市",
			"children": []
		}, {
			"value": "金东区",
			"label": "金东区",
			"children": []
		}, {
			"value": "兰溪市",
			"label": "兰溪市",
			"children": []
		}, {
			"value": "磐安县",
			"label": "磐安县",
			"children": []
		}, {
			"value": "浦江县",
			"label": "浦江县",
			"children": []
		}, {
			"value": "婺城区",
			"label": "婺城区",
			"children": []
		}, {
			"value": "武义县",
			"label": "武义县",
			"children": []
		}, {
			"value": "义乌市",
			"label": "义乌市",
			"children": []
		}, {
			"value": "永康市",
			"label": "永康市",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "丽水市",
		"label": "丽水市",
		"children": [{
			"value": "缙云县",
			"label": "缙云县",
			"children": []
		}, {
			"value": "景宁畲族自治县",
			"label": "景宁畲族自治县",
			"children": []
		}, {
			"value": "莲都区",
			"label": "莲都区",
			"children": []
		}, {
			"value": "龙泉市",
			"label": "龙泉市",
			"children": []
		}, {
			"value": "青田县",
			"label": "青田县",
			"children": []
		}, {
			"value": "庆元县",
			"label": "庆元县",
			"children": []
		}, {
			"value": "松阳县",
			"label": "松阳县",
			"children": []
		}, {
			"value": "遂昌县",
			"label": "遂昌县",
			"children": []
		}, {
			"value": "云和县",
			"label": "云和县",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "宁波市",
		"label": "宁波市",
		"children": [{
			"value": "北仑区",
			"label": "北仑区",
			"children": []
		}, {
			"value": "慈溪市",
			"label": "慈溪市",
			"children": []
		}, {
			"value": "奉化市",
			"label": "奉化市",
			"children": []
		}, {
			"value": "海曙区",
			"label": "海曙区",
			"children": []
		}, {
			"value": "江北区",
			"label": "江北区",
			"children": []
		}, {
			"value": "江东区",
			"label": "江东区",
			"children": []
		}, {
			"value": "宁海县",
			"label": "宁海县",
			"children": []
		}, {
			"value": "象山县",
			"label": "象山县",
			"children": []
		}, {
			"value": "鄞州区",
			"label": "鄞州区",
			"children": []
		}, {
			"value": "余姚市",
			"label": "余姚市",
			"children": []
		}, {
			"value": "镇海区",
			"label": "镇海区",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "衢州市",
		"label": "衢州市",
		"children": [{
			"value": "常山县",
			"label": "常山县",
			"children": []
		}, {
			"value": "江山市",
			"label": "江山市",
			"children": []
		}, {
			"value": "开化县",
			"label": "开化县",
			"children": []
		}, {
			"value": "柯城区",
			"label": "柯城区",
			"children": []
		}, {
			"value": "龙游县",
			"label": "龙游县",
			"children": []
		}, {
			"value": "衢江区",
			"label": "衢江区",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "绍兴市",
		"label": "绍兴市",
		"children": [{
			"value": "柯桥区",
			"label": "柯桥区",
			"children": []
		}, {
			"value": "上虞区",
			"label": "上虞区",
			"children": []
		}, {
			"value": "嵊州市",
			"label": "嵊州市",
			"children": []
		}, {
			"value": "新昌县",
			"label": "新昌县",
			"children": []
		}, {
			"value": "越城区",
			"label": "越城区",
			"children": []
		}, {
			"value": "诸暨市",
			"label": "诸暨市",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "台州市",
		"label": "台州市",
		"children": [{
			"value": "黄岩区",
			"label": "黄岩区",
			"children": []
		}, {
			"value": "椒江区",
			"label": "椒江区",
			"children": []
		}, {
			"value": "临海市",
			"label": "临海市",
			"children": []
		}, {
			"value": "路桥区",
			"label": "路桥区",
			"children": []
		}, {
			"value": "三门县",
			"label": "三门县",
			"children": []
		}, {
			"value": "天台县",
			"label": "天台县",
			"children": []
		}, {
			"value": "温岭市",
			"label": "温岭市",
			"children": []
		}, {
			"value": "仙居县",
			"label": "仙居县",
			"children": []
		}, {
			"value": "玉环县",
			"label": "玉环县",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "温州市",
		"label": "温州市",
		"children": [{
			"value": "苍南县",
			"label": "苍南县",
			"children": []
		}, {
			"value": "洞头县",
			"label": "洞头县",
			"children": []
		}, {
			"value": "龙湾区",
			"label": "龙湾区",
			"children": []
		}, {
			"value": "鹿城区",
			"label": "鹿城区",
			"children": []
		}, {
			"value": "瓯海区",
			"label": "瓯海区",
			"children": []
		}, {
			"value": "平阳县",
			"label": "平阳县",
			"children": []
		}, {
			"value": "瑞安市",
			"label": "瑞安市",
			"children": []
		}, {
			"value": "泰顺县",
			"label": "泰顺县",
			"children": []
		}, {
			"value": "文成县",
			"label": "文成县",
			"children": []
		}, {
			"value": "永嘉县",
			"label": "永嘉县",
			"children": []
		}, {
			"value": "乐清市",
			"label": "乐清市",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}, {
		"value": "舟山市",
		"label": "舟山市",
		"children": [{
			"value": "岱山县",
			"label": "岱山县",
			"children": []
		}, {
			"value": "定海区",
			"label": "定海区",
			"children": []
		}, {
			"value": "普陀区",
			"label": "普陀区",
			"children": []
		}, {
			"value": "嵊泗县",
			"label": "嵊泗县",
			"children": []
		}, {
			"value": "其它区",
			"label": "其它区",
			"children": []
		}]
	}]
}];

export default data01;